Added Doc Strings for the functions in "helpers.py" and "infer.py"
mindsdb/type_infer pull request #34
Opened 2023-01-30 10:58 UTC by Sumanth077

2023-01-31 15:02 UTC, paxcema requested changes
Looks really good! I have left one minor request, but once you've addressed it we can merge this :)

2023-01-31 15:02 UTC, paxcema commented on type_infer/helpers.py
> +    The function takes in a string and checks if any of its characters are alphanumeric, returning True if found and False if not.
Rephrase as:

> Check and return whether any of the input string characters are alphanumeric.

2023-01-31 15:13 UTC, Sumanth077 commented on type_infer/helpers.py
> +    The function takes in a string and checks if any of its characters are alphanumeric, returning True if found and False if not.
Updated it @paxcema.

2023-01-31 15:15 UTC, paxcema approved these changes

2023-01-31 15:29 UTC, paxcema requested changes
Lint checks are failing. Could you please add `  # noqa` to the end of all new docstrings?

2023-01-31 15:42 UTC, Sumanth077 commented
Updated it @paxcema. Could you kindly check now.

2023-06-09 23:41 UTC, paxcema commented
@Sumanth077 apologies! I somehow forgot to comment on this, but it looks OK! 

Could you perhaps merge `staging` against it to solve conflicts, so that we can merge?

2023-08-17 18:36 UTC, paxcema commented
Closing for now. Feel free to reopen whenever you have some time @Sumanth077!

2023-08-17 18:36 UTC, closed without merging